@extends('Website.Layout.main')
@section('title', 'Home')
@section('content')
    @include('Website.Layout.banner')
    @include('Website.Layout.about')
    @include('Website.Layout.slider')
    @include('Website.Layout.event')
    @include('Website.Layout.services')
    @include('Website.Layout.team')
    @include('Website.Layout.testimonial')
    @include('Website.Layout.blogAndNews')
    @include('Website.Layout.brands')
@endsection
